// Regenerate pinned country names + CLDR legal tender metadata. No user data.
import { writeFile } from 'node:fs/promises';
const json = async (url) => {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: ${response.status}`);
  return response.json();
};
const root = 'https://raw.githubusercontent.com/umpirsky/country-list/master/data';
const [ko, en, cldr] = await Promise.all([
  json(`${root}/ko/country.json`), json(`${root}/en/country.json`),
  json('https://raw.githubusercontent.com/unicode-org/cldr-json/48.0.0/cldr-json/cldr-core/supplemental/currencyData.json'),
]);
const regions = cldr.supplemental.currencyData.region;
const date = '2026-10-04';
const entries = Object.entries(ko).sort((a, b) => a[1].localeCompare(b[1], 'ko'));
const quote = (s) => JSON.stringify(s).replaceAll('$', '\\$');
const rows = entries.map(([code, name]) => {
  const currencies = (regions[code] ?? []).flatMap(Object.entries)
    .filter(([, value]) => value._tender !== 'false' &&
      (!value._from || value._from <= date) && (!value._to || value._to >= date));
  const currency = currencies[0]?.[0] ?? 'XXX'; // no general currency: never fabricate rates
  return `  '${code}': (${quote(name)}, ${quote(en[code])}, '${currency}'),`;
});
await writeFile(new URL('../lib/trip_home/models/country_catalog.dart', import.meta.url),
  `// Generated by scripts/generate_countries.mjs. Sources/licenses: docs/data-sources.md\npart of 'country.dart';\n\nconst _countryData = <String, (String, String, String)>{\n${rows.join('\n')}\n};\n`);
console.log(`${rows.length} ISO country/territory names; CLDR 48 currencies as of ${date}`);
